server:
  port: 1323
  mode: debug  # debug, release, test

database:
  path: data.db  # SQLite 数据库文件路径
  log_level: info  # silent, error, warn, info

jwt:
  secret: XC0VfuGRumdG47PqxvqC7OIDWuyGY0bUVr6+o1CHHoY=
  expire_hours: 24

log:
  level: info
  path: logs/app.log
  format: json
